utils::globalVariables(c(
  ".", ".from", ":=",
  "Additional grading criteria", "EXTRACTION_ID", "FDR_threshold",
  "FINAL CONFIDENCE GRADING", "FN", "FP", "Final", "Final_Confidence_Grading",
  "Final_Relaxed", "Final_prev_version", "Group", "Group_Regular", "Group_Relaxed",
  "Initial", "Initial_ALL", "Initial_Confidence_Grading", "Initial_WHO",
  "LOF_R", "LOF_S", "LoF_candidate", "MOI", "N", "OR", "OR_HCI",
  "OR_SOLO", "OR_SOLO_HCI", "OR_SOLO_pval_FDR_sig", "OR_SOLO_pval_max",
  "OR_SOLO_pval_rank", "OR_SOLO_pvalue", "OR_pval_max", "OR_pval_rank", "OR_pvalue",
  "PPV", "PPV_SOLO", "PPV_SOLO_ub", "PPV_ub", "PPVc_SOLO", "PPVc_SOLO_lb",
  "RDen", "RIF_geno_Regular", "RIF_geno_Relaxed", "RIF_geno_Strict",
  "RRDR_NON_SILENT", "Rcnt", "Rule_Final", "SDen", "SOLO_R", "SOLO_S",
  "SOLO_SorR", "SOnly", "Scnt", "Spec",
  "Supplementary_Grading_Considerations", "TN", "TP", "Tcnt",
  "aa_start", "absent_R", "absent_S", "add_variant", "allelic", "anyRule",
  "applyRule", "assay", "box", "category_phenotype", "checkSum",
  "correct", "correctAll", "correctSOLO", "criterion", "datasets",
  "all_lineages", "dominant_lineage", "drug", "drug_name", "drug_short", "effect", "effect_ALL",
  "extendedCandidate", "final_grading_prev_version", "gene", "genoRIF", "group",
  "final_af", "het", "het_relaxed", "het_strict", "k", "lineage", "lineage_level", "lineage_numbering", "lit_mutation",
  "literature", "max(af)", "max(quality)", "mut_R", "mut_S", "mut_S_genoRIF",
  "mutation", "n_unique", "neutral", "nomut_R", "nomut_S", "num_MOI",
  "or", "phenotype", "pos1", "pos1_ALL", "pos2", "pos2_ALL", "position",
  "predicted_effect", "present", "present_R", "present_S", "prev_version",
  "prev_version_WHO", "relevantGeno", "relevantGroup", "relevant_MOI",
  "resolved_symbol", "rm_in_sample", "rule_LoF_candidate", "rule_LoF_re_candidate",
  "sample_id", "satisfying", "selected", "setA", "setA_WHO", "setB", "setB_WHO",
  "setC", "setC_WHO", "setD", "setD_WHO", "setE", "setE_WHO", "setF",
  "stage", "tail", "temp", "testResult", "tier", "ties", "total", "totalR",
  "useLineageData", "variant", "variant_category"
))
